steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/_PROJECT_ID_/my-python-app-repo/my-flask-app:latest', '.']

# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/_PROJECT_ID_/my-python-app-repo/my-flask-app:latest']

# 3. Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'my-flask-app-service'
    - '--image=us-central1-docker.pkg.dev/_PROJECT_ID_/my-python-app-repo/my-flask-app:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'

images:
- 'us-central1-docker.pkg.dev/_PROJECT_ID_/my-python-app-repo/my-flask-app:latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET