steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/_PROJECT_ID_/my-python-app-repo/my-flask-app:latest', '.']
# 2. Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-python-app-repo/my-flask-app:latest']
# 3. Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
entrypoint: gcloud
args:
- 'run'
- 'deploy'
- 'my-flask-app-service' # Name of your Cloud Run service
- '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/my-python-app-repo/my-flask-app:latest'
- '--region=us-central1'
- '--platform=managed'
- '--allow-unauthenticated' # Makes the service public
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-python-app-repo/my-flask-app:latest'